#!/bin/sh

BUNDLE_FILE_PATTERN="specification/versions/gridtariffapi-v"

if git diff --cached --name-only | grep -q "$BUNDLE_FILE_PATTERN"; then
  echo "❌ ERROR: Generated bundle files ($BUNDLE_FILE_PATTERN*) should only be modified by GitHub Actions!"
  echo "➡️  Revert any changes to the following files before commit:"
  git diff --cached --name-only | grep "$BUNDLE_FILE_PATTERN"
  exit 1
fi

exit 0
