name: Bundle and store current API version

on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest

    env:
      INDEX_FILE: specification/gridtariffapi.json
      ARTIFACT_PREFIX: gridtariffapi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenAPI CLI and jq
        run: |
          npm install -g @redocly/openapi-cli
          sudo apt-get install -y jq

      - name: Extract OpenAPI Version
        id: get_version
        run: |
          VERSION=$(jq -r '.info.version' $INDEX_FILE)
          echo "Extracted OpenAPI version: $VERSION"
          echo "OPENAPI_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate OpenAPI Bundle
        run: |
          mkdir -p specification/versions
          NEW_BUNDLE_FILE="specification/versions/gridtariffapi-v$OPENAPI_VERSION.json"
          echo "Bundling OpenAPI specification to $NEW_BUNDLE_FILE"
          openapi bundle $INDEX_FILE -o $NEW_BUNDLE_FILE
          echo "BUNDLE_FILE=$NEW_BUNDLE_FILE" >> $GITHUB_ENV

      - name: Check for Approval
        run: |
          echo "Do you want to store the current API version into file $BUNDLE_FILE?"
          if [ "${{ github.event.inputs.approve }}" != "APPROVE" ]; then
            echo "Approval not given. Exiting..."
            exit 1
          fi
          echo "Approval received. Proceeding with Git commit and push of file $BUNDLE_FILE."

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git add $BUNDLE_FILE
          git commit -m "Auto-generate $BUNDLE_FILE from GitHub Actions" || echo "No changes to commit"
          git push
