name: OpenAPI Bundle

on:
  push:
    paths:
      - 'specification/**'
    branches:
      - main
  pull_request:
    paths:
      - 'specification/**'
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest

    env:
      INDEX_FILE: specification/gridtariffapi.json
      ARTIFACT_PREFIX: gridtariffapi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenAPI CLI and jq
        run: |
          npm install -g @redocly/openapi-cli
          sudo apt-get install -y jq

      - name: Extract OpenAPI Version
        id: get_version
        run: |
          VERSION=$(jq -r '.info.version' $INDEX_FILE)
          echo "Extracted OpenAPI version: $VERSION"
          echo "OPENAPI_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate OpenAPI Bundle
        run: |
          mkdir -p specification/versions
          NEW_BUNDLE_FILE="specification/versions/gridtariffapi-v$OPENAPI_VERSION.json"
          echo "Bundling OpenAPI specification to $NEW_BUNDLE_FILE"
          openapi bundle $INDEX_FILE -o $NEW_BUNDLE_FILE
          echo "BUNDLE_FILE=$NEW_BUNDLE_FILE" >> $GITHUB_ENV

      - name: Upload Bundle as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_PREFIX }}-${{ env.OPENAPI_VERSION }}
          path: ${{ env.BUNDLE_FILE }}
